<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/managerStyle.css">
	<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/managerMainPage.css">
	
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
	<title>Manager Transactions</title>
</head>
<body>
	<jsp:include page="_header.jsp"></jsp:include>
    <jsp:include page="_menu.jsp"></jsp:include>	
	<div class="mainmenu">
	<ul>
	<li>
		<a href="${pageContext.request.contextPath}/managers/employeeList">Employee List</a>
		<div class="menutooltip">
			View List of Employees
		</div>
	</li>
	<li>
		<a href="${pageContext.request.contextPath}/managers/salesReport">Sales Report</a>
		<div class="menutooltip">
			Obtain a sales report for a particular month
		</div>
	</li>
	<li>
		<a href="${pageContext.request.contextPath}/managers/stockList">Stock List</a>
		<div class="menutooltip">
			View List of Stocks
		</div>
	</li>
	<li>
		<a href="${pageContext.request.contextPath}/managers/orderList"> Order List</a>
		<div class="menutooltip">
			View list of orders by stock or customer name
		</div>
	</li>
	<li>	
		<a href="${pageContext.request.contextPath}/managers/summaryListing">Summary Listing</a><br>
		<div class="menutooltip" style="width:200px;">
			Produce Listing of revenue generated by a stock, stock type, or customer
		</div>
	</li>
	<li>
		<a href="${pageContext.request.contextPath}/managers/mostGeneratedRevenue">View customer and representative that generated most revenue</a><br>
	</li>
	<li>
				<a href="${pageContext.request.contextPath}/managers/backup">Backup Files</a><br>
		
	</li>
	</ul>
	</div>	
	<a class="returnbtn" href="${pageContext.request.contextPath}">Return to main page</a>
	<jsp:include page="_footer.jsp"></jsp:include>
</body>
</html>