package utils;

public class MiscUtil {

	
	public static boolean isValidState(String state){
		if(state.toUpperCase().equals("ALASKA")
				||state.toUpperCase().equals("ALABAMA")
				||state.toUpperCase().equals("ARIZONA")
				||state.toUpperCase().equals("ARKANSAS")
				||state.toUpperCase().equals("CALIFORNIA")
				||state.toUpperCase().equals("COLORADO")
				||state.toUpperCase().equals("CONNECTICUT")
				||state.toUpperCase().equals("DELAWARE")
				||state.toUpperCase().equals("FLORIDA")
				||state.toUpperCase().equals("GEORGIA")
				||state.toUpperCase().equals("HAWAII")
				||state.toUpperCase().equals("IDAHO")
				||state.toUpperCase().equals("ILLINOIS")
				||state.toUpperCase().equals("INDIANA")
				||state.toUpperCase().equals("IOWA")
				||state.toUpperCase().equals("KANSAS")
				||state.toUpperCase().equals("KENTUCKY")
				||state.toUpperCase().equals("LOUISIANA")
				||state.toUpperCase().equals("MAINE")
				||state.toUpperCase().equals("MARYLAND")
				||state.toUpperCase().equals("MASSACHUSETTS")
				||state.toUpperCase().equals("MICHIGAN")
				||state.toUpperCase().equals("MINNESOTA")
				||state.toUpperCase().equals("MISSISSIPPI")
				||state.toUpperCase().equals("MISSOURI")
				||state.toUpperCase().equals("MONTANA")
				||state.toUpperCase().equals("NEBRASKA")
				||state.toUpperCase().equals("NEVADA")
				||state.toUpperCase().equals("NEW HAMPSHIRE")
				||state.toUpperCase().equals("NEW JERSEY")
				||state.toUpperCase().equals("NEW MEXICO")
				||state.toUpperCase().equals("NEW YORK")
				||state.toUpperCase().equals("NORTH CAROLINA")
				||state.toUpperCase().equals("NORTH DAKOTA")
				||state.toUpperCase().equals("OHIO")
				||state.toUpperCase().equals("OKLAHOMA")
				||state.toUpperCase().equals("OREGON")
				||state.toUpperCase().equals("PENNSYLAVANIA")
				||state.toUpperCase().equals("RHODE ISLAND")
				||state.toUpperCase().equals("SOUTH CAROLINA")
				||state.toUpperCase().equals("SOUTH DAKOTA")
				||state.toUpperCase().equals("TENNESSEE")
				||state.toUpperCase().equals("TEXAS")
				||state.toUpperCase().equals("UTAH")
				||state.toUpperCase().equals("VERMONT")
				||state.toUpperCase().equals("VIRGINIA")
				||state.toUpperCase().equals("WASHINGTON")
				||state.toUpperCase().equals("WEST VIRGINIA")
				||state.toUpperCase().equals("WISCONSIN")
				||state.toUpperCase().equals("WYOMING")
				||state.toUpperCase().equals("WASHINGTON D.C.")
				||state.toUpperCase().equals("DISTRICT OF COLUMBIA")
				||state.toUpperCase().equals("ALABAMA")
				||state.toUpperCase().equals("AL")
				||state.toUpperCase().equals("AK")
				||state.toUpperCase().equals("AZ")
				||state.toUpperCase().equals("AR")
				||state.toUpperCase().equals("CA")
				||state.toUpperCase().equals("CO")
				||state.toUpperCase().equals("CT")
				||state.toUpperCase().equals("DE")
				||state.toUpperCase().equals("FL")
				||state.toUpperCase().equals("GA")
				||state.toUpperCase().equals("HI")
				||state.toUpperCase().equals("ID")
				||state.toUpperCase().equals("IL")
				||state.toUpperCase().equals("IN")
				||state.toUpperCase().equals("IA")
				||state.toUpperCase().equals("KS")
				||state.toUpperCase().equals("KY")
				||state.toUpperCase().equals("LA")
				||state.toUpperCase().equals("ME")
				||state.toUpperCase().equals("MD")
				||state.toUpperCase().equals("MA")
				||state.toUpperCase().equals("MI")
				||state.toUpperCase().equals("MN")
				||state.toUpperCase().equals("MS")
				||state.toUpperCase().equals("MO")
				||state.toUpperCase().equals("MT")
				||state.toUpperCase().equals("NE")
				||state.toUpperCase().equals("NV")
				||state.toUpperCase().equals("NH")
				||state.toUpperCase().equals("NJ")
				||state.toUpperCase().equals("NY")
				||state.toUpperCase().equals("NC")
				||state.toUpperCase().equals("ND")
				||state.toUpperCase().equals("OH")
				||state.toUpperCase().equals("OK")
				||state.toUpperCase().equals("OR")
				||state.toUpperCase().equals("PA")
				||state.toUpperCase().equals("RI")
				||state.toUpperCase().equals("SC")
				||state.toUpperCase().equals("SD")
				||state.toUpperCase().equals("TN")
				||state.toUpperCase().equals("TX")
				||state.toUpperCase().equals("UT")
				||state.toUpperCase().equals("VT")
				||state.toUpperCase().equals("VA")
				||state.toUpperCase().equals("WA")
				||state.toUpperCase().equals("WV")
				||state.toUpperCase().equals("WI")
				||state.toUpperCase().equals("WY")
				||state.toUpperCase().equals("DC"))
			return true;
		
		
		return false;
	}
	
}
